[package]
name = "veris-net"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true}
sqlparser = { workspace = true}
thiserror = {workspace = true}
tokio = { workspace = true}
toml = {workspace = true}
